
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cardGame
{
public partial class EmotionCardReaderDB
{
    private readonly System.Collections.Generic.Dictionary<string, cardGame.EmotionCardDB> _dataMap;
    private readonly System.Collections.Generic.List<cardGame.EmotionCardDB> _dataList;
    
    public EmotionCardReaderDB(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, cardGame.EmotionCardDB>();
        _dataList = new System.Collections.Generic.List<cardGame.EmotionCardDB>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cardGame.EmotionCardDB _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.cardGame.EmotionCardDB.DeserializeEmotionCardDB(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, cardGame.EmotionCardDB> DataMap => _dataMap;
    public System.Collections.Generic.List<cardGame.EmotionCardDB> DataList => _dataList;

    public cardGame.EmotionCardDB GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cardGame.EmotionCardDB Get(string key) => _dataMap[key];
    public cardGame.EmotionCardDB this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

