
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.cardGame
{ 
    public enum EmotionType
    {
        /// <summary>
        /// 喜悦
        /// </summary>
        Happy = 0,
        /// <summary>
        /// 悲伤
        /// </summary>
        Sad = 1,
        /// <summary>
        /// 愤怒
        /// </summary>
        Angry = 2,
    }

} 

