
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cardGame
{
public sealed partial class NormalCardDB : Luban.BeanBase
{
    public NormalCardDB(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["emotion"].IsNumber) { throw new SerializationException(); }  Emotion = (cardGame.EmotionType)_buf["emotion"].AsInt; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["iconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["iconPath"]; }
    }

    public static NormalCardDB DeserializeNormalCardDB(JSONNode _buf)
    {
        return new cardGame.NormalCardDB(_buf);
    }

    /// <summary>
    /// 普通卡牌ID
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 情绪类型
    /// </summary>
    public readonly cardGame.EmotionType Emotion;
    /// <summary>
    /// 情绪等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 卡牌图标路径
    /// </summary>
    public readonly string IconPath;
   
    public const int __ID__ = 178524865;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "emotion:" + Emotion + ","
        + "level:" + Level + ","
        + "description:" + Description + ","
        + "iconPath:" + IconPath + ","
        + "}";
    }
}

}

