
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.cardGame
{ 
    public enum RareType
    {
        /// <summary>
        /// 常见
        /// </summary>
        N = 0,
        /// <summary>
        /// 稀有
        /// </summary>
        R = 1,
        /// <summary>
        /// 史诗
        /// </summary>
        SR = 2,
        /// <summary>
        /// 限定
        /// </summary>
        SSR = 3,
    }

} 

