
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dialog
{
public sealed partial class DiglogDB : Luban.BeanBase
{
    public DiglogDB(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["text"].IsString) { throw new SerializationException(); }  Text = _buf["text"]; }
        { if(!_buf["nextID"].IsString) { throw new SerializationException(); }  NextID = _buf["nextID"]; }
    }

    public static DiglogDB DeserializeDiglogDB(JSONNode _buf)
    {
        return new dialog.DiglogDB(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Text;
    public readonly string NextID;
   
    public const int __ID__ = -647122554;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "text:" + Text + ","
        + "nextID:" + NextID + ","
        + "}";
    }
}

}

