
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.phone
{
public partial class MessageReaderDB
{
    private readonly System.Collections.Generic.Dictionary<string, phone.MessageDB> _dataMap;
    private readonly System.Collections.Generic.List<phone.MessageDB> _dataList;
    
    public MessageReaderDB(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, phone.MessageDB>();
        _dataList = new System.Collections.Generic.List<phone.MessageDB>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            phone.MessageDB _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.phone.MessageDB.DeserializeMessageDB(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, phone.MessageDB> DataMap => _dataMap;
    public System.Collections.Generic.List<phone.MessageDB> DataList => _dataList;

    public phone.MessageDB GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public phone.MessageDB Get(string key) => _dataMap[key];
    public phone.MessageDB this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

