
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.phone
{
public sealed partial class MessageDB : Luban.BeanBase
{
    public MessageDB(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["sender"].IsString) { throw new SerializationException(); }  Sender = _buf["sender"]; }
        { if(!_buf["iconpath"].IsString) { throw new SerializationException(); }  Iconpath = _buf["iconpath"]; }
        { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
    }

    public static MessageDB DeserializeMessageDB(JSONNode _buf)
    {
        return new phone.MessageDB(_buf);
    }

    /// <summary>
    /// 信息ID
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 发送者
    /// </summary>
    public readonly string Sender;
    /// <summary>
    /// 图标的路径
    /// </summary>
    public readonly string Iconpath;
    /// <summary>
    /// 信息内容
    /// </summary>
    public readonly string Content;
   
    public const int __ID__ = -1874370011;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "sender:" + Sender + ","
        + "iconpath:" + Iconpath + ","
        + "content:" + Content + ","
        + "}";
    }
}

}

