
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.schedule
{
public partial class DateReaderDB
{
    private readonly System.Collections.Generic.Dictionary<int, schedule.DateCardsDB> _dataMap;
    private readonly System.Collections.Generic.List<schedule.DateCardsDB> _dataList;
    
    public DateReaderDB(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, schedule.DateCardsDB>();
        _dataList = new System.Collections.Generic.List<schedule.DateCardsDB>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            schedule.DateCardsDB _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.schedule.DateCardsDB.DeserializeDateCardsDB(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, schedule.DateCardsDB> DataMap => _dataMap;
    public System.Collections.Generic.List<schedule.DateCardsDB> DataList => _dataList;

    public schedule.DateCardsDB GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public schedule.DateCardsDB Get(int key) => _dataMap[key];
    public schedule.DateCardsDB this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

