
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.schedule
{
public sealed partial class DateCardsDB : Luban.BeanBase
{
    public DateCardsDB(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["DateName"].IsString) { throw new SerializationException(); }  DateName = _buf["DateName"]; }
        { if(!_buf["Unlocked"].IsBoolean) { throw new SerializationException(); }  Unlocked = _buf["Unlocked"]; }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
        { if(!_buf["SchuduledAction"].IsObject) { throw new SerializationException(); }  SchuduledAction = global::cfg.schedule.DateAction.DeserializeDateAction(_buf["SchuduledAction"]);  }
    }

    public static DateCardsDB DeserializeDateCardsDB(JSONNode _buf)
    {
        return new schedule.DateCardsDB(_buf);
    }

    /// <summary>
    /// 日程ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 日程名称
    /// </summary>
    public readonly string DateName;
    /// <summary>
    /// 是否解锁 这里填初始的解锁状态
    /// </summary>
    public readonly bool Unlocked;
    /// <summary>
    /// 图标的文件位置
    /// </summary>
    public readonly string IconPath;
    public readonly schedule.DateAction SchuduledAction;
   
    public const int __ID__ = 66695836;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SchuduledAction?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "DateName:" + DateName + ","
        + "Unlocked:" + Unlocked + ","
        + "IconPath:" + IconPath + ","
        + "SchuduledAction:" + SchuduledAction + ","
        + "}";
    }
}

}

