
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.schedule
{
public abstract partial class DateAction : Luban.BeanBase
{
    public DateAction(JSONNode _buf) 
    {
    }

    public static DateAction DeserializeDateAction(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "Notice": return new schedule.Notice(_buf);
            case "Course": return new schedule.Course(_buf);
            case "Work": return new schedule.Work(_buf);
            case "Rest": return new schedule.Rest(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

