
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.schedule
{
public sealed partial class Notice : DateAction
{
    public Notice(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["ContinueDays"].IsNumber) { throw new SerializationException(); }  ContinueDays = _buf["ContinueDays"]; }
        { if(!_buf["FirstMoney"].IsNumber) { throw new SerializationException(); }  FirstMoney = _buf["FirstMoney"]; }
        { if(!_buf["EndMoney"].IsNumber) { throw new SerializationException(); }  EndMoney = _buf["EndMoney"]; }
        { if(!_buf["MoodReduce"].IsNumber) { throw new SerializationException(); }  MoodReduce = _buf["MoodReduce"]; }
    }

    public static Notice DeserializeNotice(JSONNode _buf)
    {
        return new schedule.Notice(_buf);
    }

    public readonly int ContinueDays;
    public readonly int FirstMoney;
    public readonly int EndMoney;
    public readonly int MoodReduce;
   
    public const int __ID__ = 151899695;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ContinueDays:" + ContinueDays + ","
        + "FirstMoney:" + FirstMoney + ","
        + "EndMoney:" + EndMoney + ","
        + "MoodReduce:" + MoodReduce + ","
        + "}";
    }
}

}

