
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.schedule
{
public sealed partial class Rest : DateAction
{
    public Rest(JSONNode _buf)  : base(_buf) 
    {
    }

    public static Rest DeserializeRest(JSONNode _buf)
    {
        return new schedule.Rest(_buf);
    }

   
    public const int __ID__ = 1631550699;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

