
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public schedule.DateReaderDB DateReaderDB {get; }
    public phone.MessageReaderDB MessageReaderDB {get; }
    public dialog.DialogReaderDB DialogReaderDB {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        DateReaderDB = new schedule.DateReaderDB(loader("schedule_datereaderdb"));
        MessageReaderDB = new phone.MessageReaderDB(loader("phone_messagereaderdb"));
        DialogReaderDB = new dialog.DialogReaderDB(loader("dialog_dialogreaderdb"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        DateReaderDB.ResolveRef(this);
        MessageReaderDB.ResolveRef(this);
        DialogReaderDB.ResolveRef(this);
    }
}

}
